# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190401_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
