# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190403_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.User'),
        ),
        migrations.AlterField(
            model_name='status',
            name='value',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
