# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 09:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20190403_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_logged_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 3, 9, 23, 11, 284659, tzinfo=utc), verbose_name='last logged in'),
        ),
    ]
