# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 10:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_user_last_logged_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_logged_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 3, 10, 35, 53, 650255, tzinfo=utc), verbose_name='last logged in'),
        ),
    ]
