# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 10:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20190403_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_logged_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 3, 10, 36, 45, 100997, tzinfo=utc), verbose_name='last logged in'),
        ),
    ]
