# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20190403_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_logged_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 3, 11, 53, 17, 14961, tzinfo=utc), verbose_name='last logged in'),
        ),
    ]
