
MSG_ALREADY_LOGGED_IN = "You are already logged in"
MSG_ALREADY_REGISTERED = "you are already registered"
USER_LOGIN_VALUE="LOGIN"
USER_LOGOUT_VALUE="LOGOUT"
USER_SIGNIN_VALUE="SIGNIN"
USER_SIGNOUT_VALUE="SIGNOUT"
USER_STATUS_KEY="STATUS"
USER_PAGE_KEY="PAGE"
USER_URL_WRITE_KEY="write"
USER_URL_LOGIN_KEY="login"
USER_URL_INDEX_KEY="index"
USER_URL_PROFILE_KEY="profile"

